/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "surface-container": "#171f33",
              "surface-container-low": "#131b2e",
              "on-surface-variant": "#c2c6d6",
              "on-secondary-container": "#aeb9d0",
              "surface-container-lowest": "#060e20",
              "on-tertiary-container": "#0d0096",
              "primary": "#adc6ff",
              "inverse-surface": "#dae2fd",
              "primary-container": "#4d8eff",
              "tertiary": "#c0c1ff",
              "surface-tint": "#adc6ff",
              "secondary": "#bcc7de",
              "on-secondary-fixed-variant": "#3c475a",
              "outline": "#8c909f",
              "on-primary-container": "#00285d",
              "primary-fixed-dim": "#adc6ff",
              "on-primary-fixed": "#001a42",
              "secondary-container": "#3e495d",
              "error": "#ffb4ab",
              "tertiary-container": "#8083ff",
              "background": "#0b1326",
              "on-background": "#dae2fd",
              "on-secondary": "#263143",
              "tertiary-fixed": "#e1e0ff",
              "on-tertiary-fixed-variant": "#2f2ebe",
              "tertiary-fixed-dim": "#c0c1ff",
              "on-error": "#690005",
              "secondary-fixed": "#d8e3fb",
              "on-secondary-fixed": "#111c2d",
              "on-tertiary-fixed": "#07006c",
              "inverse-primary": "#005ac2",
              "inverse-on-surface": "#283044",
              "surface-container-high": "#222a3d",
              "secondary-fixed-dim": "#bcc7de",
              "on-primary-fixed-variant": "#004395",
              "surface-container-highest": "#2d3449",
              "primary-fixed": "#d8e2ff",
              "on-surface": "#dae2fd",
              "error-container": "#93000a",
              "on-error-container": "#ffdad6",
              "surface-dim": "#0b1326",
              "surface": "#0b1326",
              "on-primary": "#002e6a",
              "surface-variant": "#2d3449",
              "outline-variant": "#424754",
              "on-tertiary": "#1000a9",
              "surface-bright": "#31394d"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "md": "16px",
              "xl": "40px",
              "xs": "4px",
              "container_max": "1440px",
              "xxl": "64px",
              "lg": "24px",
              "sm": "8px",
              "gutter": "20px",
              "base": "4px"
      },
      "fontFamily": {
              "headline-lg-mobile": ["Geist"],
              "body-md": ["Inter"],
              "label-md": ["Geist"],
              "headline-md": ["Geist"],
              "headline-lg": ["Geist"],
              "body-lg": ["Inter"],
              "label-sm": ["Geist"],
              "display-lg": ["Geist"]
      },
      "fontSize": {
              "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500"}],
              "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
              "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
